### ISSUE TITLE
Is it possible to use tailwindcss-ripple with daisyui?

### ISSUE THREAD

**Issue by samiulalimsaad** [jamessessford/tailwindcss-ripple#22]

**Comment by jamessessford** [comment]
Hiya!

I haven't played with daisyui so can't be 100% certain but if you have access to a tailwind config file, this should definitely work!

If you give it a try and it doesn't, let me know and I can take a look!

Cheers,
James

**Comment by samiulalimsaad** [comment]
This is my `tailwind.config.js` configuration

```js
module.exports = {
    content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
    theme: {
        ripple: (theme) => ({
            colors: theme("colors"),
        }),
    },
    plugins: [require("daisyui"), require("tailwindcss-ripple")()],
};
```

according to `tailwindcss-ripple` if i use

```js
plugins: [require("daisyui"), require("tailwindcss-ripple")()],
```

it's not working also showing this error

![image](https://user-images.githubusercontent.com/57401611/169567921-6e7f62a6-c3e0-4dd5-87d7-870684410264.png)


and if i don't call then it's also not working.

```js
plugins: [require("daisyui"), require("tailwindcss-ripple")],
```

this is my repo [link](https://github.com/samiulalimsaad/daisyui-test) you can check this out.

**Comment by jamessessford** [comment]
Hiya,

I tried this out this morning and was able to get it working by using the following config

```js
// tailwind.config.js
const colors = require('tailwindcss/colors')

module.exports = {
    content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
    theme: {
        ripple: () => ({
            colors,
        }),
    },
    plugins: [require("daisyui"), require('tailwindcss-ripple')()],
};

```

I think the problem is the change in how the colors are listed in version 3 of Tailwind. Can you give this a shot and let me know if it works for you?

Cheers

**Comment by samiulalimsaad** [comment]
Works. 
Thanks 👍

**Comment by jamessessford** [comment]
You're welcome, glad I could help!
