### ISSUE TITLE
Enable customisable parameters

### ISSUE THREAD

**Issue by RhysyG** [jamessessford/tailwindcss-ripple#3]
Hey, nice plugin.
Thanks for doing the Tailwind integration.

Is it possible to add customisable parameters?
For example, I find the darken(0.2) a bit too dark.

Thanks.

**Comment by jamessessford** [comment]
Hi @RhysyG,

Cheers! Tailwind is a lot of fun to work with. Yeah I don't think that should be a problem. I've got some time over the next few days so I'll have a look at it for you!

**Comment by jamessessford** [comment]
Hey @RhysyG - I've just pushed a new version of the package (#4) that allows the darken value to be passed as a parameter in the config. 

I'll close the issue off but please get back in touch if this doesn't help :)

Thanks and enjoy the weekend!
