### ISSUE TITLE
Smoother/slower transition?

### ISSUE THREAD

**Issue by rjworks** [jamessessford/tailwindcss-ripple#9]
Is there a way to slower/smoothen the speed of the effect? I find it a bit too fast

**Comment by jamessessford** [comment]
Hey!

There isn't currently but it's probably something I can expose as a config option if that would help?

**Comment by rjworks** [comment]
That would be awesome thanks

**Comment by jamessessford** [comment]
Sweet, I'll try and take a look at it over the next couple days,

Cheers!

**Comment by jamessessford** [comment]
Hey! 

So this looks totally doable but wanted to sound you out about how you think this should be approached:

1. I can expose a config option just for timing; You'd only be able to set how long the transition takes (with the current as default)
2. I expose the config option as a string and you'd have full control over the transition that's assembled (with the current as default)

Cheers!

**Comment by rjworks** [comment]
I think option 2 is better

**Comment by jamessessford** [comment]
I thought so too! I've updated the script now, if you want to update a package.json file to point to the main branch you'll be abl

**Comment by jamessessford** [comment]
Didn't mean to close the issue off! I hit the wrong button.

I've updated the script now and updated the readme. If that covers what you were looking for I'll release the code :)

**Comment by rjworks** [comment]
thank you
